version: "3"
services:
  my-app:
    container_name: my-app
    image: nginx:latest
    volumes:
      - ./build:/usr/share/nginx/html
    ports:
      - 3002:80
networks:
  default:
    external:
      name: minicurso-network
